jonodrew/mentor-match

- matching/person.py
- matching/process.py
- tests/test_match.py
- tests/test_process.py
This is a significant PR. It puts in place everything needed to run this locally, assuming the data is in the same format as it is in the dummy spreadsheet. I've run some tests locally with garbage data, and it's hard to determine how successful it is - I'll leave that up to someone doing this as a day job!
> Complete first version

- matching/match.py
- matching/mentor.py
- matching/process.py
- tests/test_match.py
- tests/test_process.py
This PR implements the full matching process via three functions. At the moment it just returns the raw objects, so the next stage is to convert those into a more useful format for a human user.
> Matching process

- matching/mentee.py
- matching/mentor.py
- matching/person.py
- matching/process.py
- tests/conftest.py
- tests/test_match.py
- tests/test_person.py
- tests/test_process.py
This PR enables users to generate a CSV file useful for mail merges and letting people know who they're matched with
> Output to csv

- matching/helpers/pre_processing.py
- matching/match.py
- matching/person.py
- matching/process.py
- tests/conftest.py
- tests/test_match.py
- tests/test_pre_processing.py
- tests/test_process.py
This PR is a victim of scope creep. Rather than just testing generated unbalanced data, I committed fully to working through the solution. And I've been successful! All the code is now working 
It adds a test that relies on integration data - I'll fix this up later, so at the moment the test is simply skipped, because that data should only be kept locally
> Test unbalanced inputs

- matching/process.py
- tests/test_process.py
- tox.ini
...and implements mypy to make sure they don't reappear
> This fixes some small typing errors

- Dockerfile
- README.md
- app/main/routes.py
- app/static/main.js
- app/tasks.py
- app/templates/base.html
- app/templates/index.html
- docker-compose.yml
- requirements.txt
This fixes #12 
There's a few changes here. The largest and most obvious is the move to using docker and docker-compose. This may make it slightly more tricky to deploy into Heroku as expected, but I don't expect too much difficulty: we'll just end up with two apps running, as well as the hosted redis solution.
> Implement redis

- Dockerfile
- app/tasks.py
- docker-compose.yml
- heroku.yml
Should close https://github.com/jonodrew/mentor-match/projects/1#card-69001690
> Heroku deployment

- docker-compose.yml
Somewhere and somehow in fixing the Docker files I seem to have broken the dev environment. This should fix that problem!
> Fix dev environment

- .pre-commit-config.yaml
- app/helpers.py
Fix the mypy issue and implement a pre-commit hook to avoid the issues going forward
> Hotfix mypy

- .github/workflows/deploy.yml
- .github/workflows/trunk-dev.yml
Pull requests now trigger builds, while merging to main deploys
> Tidy up development approach

- app/helpers.py
- tests/conftest.py
- tests/test_integration.py
- tests/test_upload_route.py
This implements a test to check that uploading files works
> Implement input system test

- app/main/routes.py
- app/static/main.js
- app/templates/index.html
I've altered the button so that it uses the route, rather than downloading it. This is because the route itself has a post-request function that deletes the file once it's been downloaded. This prevents sensitive data hanging around on the server any longer than we need it.
> Use route to ensure deletion

- .pre-commit-config.yaml
- app/main/routes.py
- tests/test_download_route.py
This fixes #53 
Thanks to @johnpeart spotting this. I've now written a test, to prove that files are deleted, and I've manually tested.
> Fixup file deletion

- app/main/routes.py
- app/static/main.js
- app/templates/index.html
- app/templates/process.html
This fixes an error with the javascript whereby the application didn't actually do the processing.
Should have written my tests first!!
A few lines of javascript have been removed, because they were looking for a table that didn't exist. I don't propose to have the table on the 'process' page, so we don't need those lines of code
> Fix 'Process your data' button

- app/main/routes.py
- app/templates/base.html
- app/templates/cookies.html
- app/templates/index.html
- app/templates/privacy-and-data.html
This PR attempts to add two pages to the site and link them from the footer. It implements #47.
The pages are not populated with the substantive content, as we should write this after the service is built so that it is accurate.
.
> Cookies and privacy policy

- app/main/routes.py
- tests/conftest.py
- tests/test_download_route.py
- tests/test_integration.py
- tests/test_process_route.py
- tests/test_task.py
- tests/test_upload_route.py
This change:
- adds a method to delete uploaded data once it's been sent for processing
- tests that the method works
- uses `url_for` throughout to make the code easier to change in future
> Delete all files

- app/main/routes.py
- app/templates/cookies.html
- app/templates/privacy-and-data.html
- tests/test_integration.py
- tests/test_upload_route.py
Added a:
- cookie policy (based on the GOV.UK model)
- privacy policy statement (based on the existing CSLGBT+ Network policy)
@jonodrew what do you think?
There are a few 'blanks' in here to fill in and check too; principally:
- the name of the cookies
- the expiry window of the cookies
> Policy statements

- app/main/routes.py
- app/templates/process.html
I had forgotten to change the javascript, and since that's an area we don't yet test, it slipped through broken. This introduces a fix
> Fixup cookie issue

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- app/classes.py
- app/helpers.py
- app/main/routes.py
- app/static/data/large/mentees.csv
- app/static/data/large/mentors.csv
- app/static/data/small/mentees.csv
- app/static/data/small/mentors.csv
- app/tasks/tasks.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_classes.py
- tests/test_integration.py
- tests/test_task.py
This is a huge change for what seemed like a small task. The aim is for mentees to be able to selet a characteristic against which they'd like to be matched, and for mentors to be able to select some number of characteristics that they have.
To do this I've subclassed the `Mentor`, `Mentee`, and `ParticipantFactory` classes from the matching library. Consequently I've had to rewrite a fairly significant chunk of this software. However, I think it's slightly better now, with more tests and a clearer separation of concerns.
> Add characteristics

- README.md
- app/helpers.py
- sample_data/large/mentees.csv
- sample_data/large/mentors.csv
- sample_data/small/mentees.csv
- sample_data/small/mentors.csv
This change adds a function to create random data. It also adds four files of random data to the repo, for people to try out
> Random data

- .bumpversion.cfg
- app/main/routes.py
- app/tasks/tasks.py
- requirements.txt
- setup.py
- tests/test_classes.py
- tests/test_integration.py
- tests/test_task.py
The mentor-match-package has reached version 6! This removes the need for the boilerplate weightings I was forcing in and means code can be deleted, which is always great.
> Bump package major

- app/main/routes.py
- app/templates/output.html
- tests/test_download_route.py
@johnpeart 
I sincerely apologise for the ugliness of this frontend. Maybe you could do something a bit nicer? At the very least it should mean less work calculating for you.
Once this is prettified and merged, I'll start on the matching bit to allow users to specify their unmatched bonus (and maybe some of the other rules, too!)
> Unmatched bonus UI

- pytest.ini
This suppresses warnings that I've not registered some of the marks by...registering them
> Add custom marks

- .bumpversion.cfg
- app/tasks/tasks.py
- setup.py
This was only getting the better outcome where it was better for _both_ mentors and mentees, when the focus should be on mentees. This improves that
> Patch the find_best_outcome task

- .github/workflows/deploy.yml
- requirements.txt
This will automatically bump the version when a PR is merged. By default it's going to be a minor push, but this can be defined in the commit message - just ad #patch, #minor, or #major to the merge commit
> Add versioning job

- README.md
This PR adds details in the readme on how to login when running the apps locally.
> Add local login credentials to README
