jonodrew/mentor-match

- app/config.py
- app/helpers.py
- app/main/routes.py
- tests/conftest.py
- tests/test_upload_route.py
This changes the "/upload" route and does the following:
- checks if there are exactly two files, and returns an error message if not
- checks that the two files are called "mentors.csv" and "mentees.csv" and returns an error if not
- checks that the two files actually end in ".csv" to reduce security risk, and returns an error if not
Currently it does nothing at all with these files, but it's enough to start building out the frontend
> First phase of upload journey

- .github/workflows/deploy.yml
the secrets context in GitHub actions is accessed just as 'secrets', not 'github.secrets'!
> Fixup deploy action

- app/helpers.py
- app/main/routes.py
- tests/conftest.py
- tests/test_upload_route.py
When a user has uploaded their files they're saved to a random location ready for the user to commit to processing. The saved location is passed back to the user as a key in the session cookie, so it can be captured on the next page when we come to process the files.
Wider question here of whether users expect distinct "upload" and "start processing" steps, or expect both steps in one action. @johnpeart I'm going to keep the upload --> start processing journey for now, but maybe one to keep in mind for future
> Save uploaded file and put folder into session

- docker-compose.override.yml
This change fixes the volumes and ensures they're mounted in the right place, enabling developers to see the changes they're making
> Fix docker-compose.override.yml

- app/main/routes.py
- app/static/main.js
- app/templates/process.html
- tests/test_integration.py
- tests/test_process_route.py
- tests/test_upload_route.py
This change alters some underlying connections by renaming variables so that they're clearer. It also adds the 'process' section of the user journey. Some of that is replicated from the index, which will be decommissioned before long.
Actually checking if the journey works end-to-end will need me to dip into pytest-bdd to manage the user interactions - clicking next, uploading files, etc etc.
> Add 'process' user journey

- app/templates/base.html
The CSS file is a copy of the file that is on the [www.civilservice.lgbt](http://www.civilservice.lgbt/) website. That, in turn, is refreshed from a GitHub repo called ‘Magenta’ each night when the site rebuilds. 
This change directly links to the main site CSS file, rather than maintaining a separate one, so the files stay in lockstep.
This means updates to the Magenta theme are automatically reflected on this site.
> Change CSS file

- app/main/routes.py
- app/templates/input.html
This change will create the upload form, which will enable users to upload their participants ready to be matched.
As of 2022-02-10 it is pretty ugly:
And the error messages could be clearer:
However, it's a start.
> Add upload form

- .github/workflows/trunk-dev.yml
- .pre-commit-config.yaml
- app/config.py
- app/main/routes.py
- app/static/main.js
- app/tasks/__init__.py
- app/tasks/tasks.py
- app/templates/output.html
- requirements.txt
- tests/conftest.py
- tests/test_download_route.py
- tests/test_integration.py
- tests/test_process_route.py
- tests/test_task.py
- tests/test_upload_route.py
This change:
- adds a new route to the web server that allows for deletion of resources
- adds a new asynchronous task to delete the mailing lists
This is because Flask is single-threaded, so we can't even asynchronously call a function that just `sleep`s for 15 minutes as it'll block the entire application
Given that the `task_id`, which is the name of the generated folder, is immensely long and complex, I don't think there's a danger of the data being deleted by a malicious actor. 
Before this is merged, we need an environment variable in the production environment:
`FLASK_URL=https://cslgbt-mentor-match.herokuapp.com/`
And we'll need to change that once we've decided on #52
> Delete data after period

- .bumpversion.cfg
- requirements.txt
- setup.py
This bumps the mentor-match package to 4.0.1.
The pckage now exposes a `Rule` object. In future versions we'll either need to create these on the web app and send them to the Celery worker as binary, or send some kind of json/dict to the worker and have a factory recreate the rules. However, at the moment the package maintainer (me) has kindly recreated the rules in the package, so the upshot is that nothing has changed for us
For now though, all tests pass. I've done a manual review as well and everything still seems to be working fine
> Bump package version

- .bumpversion.cfg
- .github/workflows/trunk-dev.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- app/helpers.py
- app/main/routes.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_integration.py
The idiot who maintains the underlying package for this service has decided to generalise it, despite all the work we've done together. This means that our csv is no longer the template for the entire library, and I've had to write a mapping function to convert our headings into what they expect. Very frustrating but can't be helped.
Users should not experience any degradation of the service. However, we may need to consider how best to move forwards with the creation of the spreadsheet and mailing list.
This change makes it our responsibility to turn the integers representing the grade to a human-readable string - which would be fine, if the library didn't also produce our spreadsheet, which needs to be human-readable. We'll need to take control of the spreadsheet, or prevail upon the …
> Bump mentor match package 5.1.0

- app/tasks/tasks.py
This prevents a match scoring points when the mentee hasn't declared a characteristic. Without this change, people who declared no preference would be matched as highly as people who had a specific characteristic match, which seems wrong for this use case
> Don't match when mentee hasn't declared characteristic

- .bumpversion.cfg
- CHANGELOG.md
- Dockerfile
- app/classes.py
- app/config.py
- app/extensions.py
- app/helpers.py
- app/main/routes.py
- app/tasks/__init__.py
- app/tasks/helpers.py
- app/tasks/tasks.py
- docker-compose.yml
- setup.py
- tests/conftest.py
- tests/test_classes.py
- tests/test_integration.py
- tests/test_task.py
- The system now uses pickle under the hood, so please be careful - if you've not secured the connections between
the machines you're running this on you could really get yourself into trouble.
- However, it has made it significantly faster - a single matching exercise is now down to just 40s, from a best of
97s when we were using JSON to serialize data.
- This is the big one. We've added functionality that will creep up an `UnmatchedBonus`. This functionality is
useful if you want to ensure everyone gets at least one mentor. It calculates a lot of values - one client is
calculating 37 different iterations of a three-round program, requiring 111 rounds of matching - so it takes a bit
longer to calculate. Exposing this functionality in the front end will be patched very soon, but in the …
> Change task to allow a value for unmatched bonus

- .github/workflows/trunk-dev.yml
- requirements.txt
This test suite is quite easy to parallelize, because there's no database so there's no state to be worrying about. This means we can ramp up the speed of the tests very easily
> Add parallelization library

- CHANGELOG.md
- app/main/routes.py
- app/static/main.js
- app/templates/options.html
- app/templates/process.html
- tests/test_integration.py
- tests/test_upload_route.py
This adds a clean version of:
– a new route (that doesn't work!) for an /options page
– a page template for the /options page
– an amendment to the /process page that could usefully show the option people selected (but needs a way to know what that is from the router!)
> Add options

- app/templates/privacy-and-data.html
Pull request for #84.
Changes are minor only to the HTML page template for the /privacy-and-data page.
> Update privacy policy (special category data)

- .bumpversion.cfg
- CHANGELOG.md
- app/export.py
- app/helpers.py
- app/main/routes.py
- app/tasks/tasks.py
- requirements.txt
- setup.py
- tests/test_export.py
- tests/test_notify_route.py
- tests/test_task.py
- This change exposes a route that, on a `POST` request:
- reads a cookie `task-id`, which is the folder where the output is stored
- receives a form from the request, which has a `template-id`, a `reply-id`, a `service`, and an `api-key`
- the `service` defaults to Notify, so for the moment that choice doesn't need to be coded into the system
- it creates the appropriate client for the `service`, and then sends every participant, in both files in the
output folder, the `template-id` email using each row in the file as the personalisation
- the emails are handed off to Celery to take care of
- this does not yet take account of any other templates: for example, templates where no matches have been made.
These `template-id`s would need to be passed, somehow, from the frontend. …
> Notify participants

- docs/.gitignore
- docs/CNAME
- docs/_config.yml
- docs/_docs/second-test-document.md
- docs/_docs/test-document.md
- docs/index.md
This pull request sets up the basics for issue #108 and adds Jekyll / Github Pages for documentation.
> Add Jekyll docs

- .bumpversion.cfg
- CHANGELOG.md
- app/__init__.py
- app/classes.py
- app/export.py
- app/helpers.py
- app/main/routes.py
- app/notify/__init__.py
- app/notify/routes.py
- app/static/main.js
- app/tasks/tasks.py
- app/templates/notify-settings/notify-settings--api-key.html
- app/templates/notify-settings/notify-settings--reply-to.html
- app/templates/notify-settings/notify-settings--template-ids.html
- app/templates/notify-settings/notify-settings-intro.html
- setup.py
- tests/test_classes.py
- tests/test_export.py
- tests/test_integration.py
- tests/test_notify_client.py
- tests/test_notify_route.py
Should fix #109 
This is a great big chunk of work, and it's still not quite finished. We need a neat way to tie together the matching workflow and this notifications workflow. Ideas welcome.
However, for now, you can test this by going through the matching workflow, and then going to `/notify-settings/before-you-start`. From there, follow the workflow through.
ONLY USE A TEST API KEY. This service is genuinely connected to the genuine internet and will genuinely email a whole bunch of people if you tell it to.
So don't!
Okay, that's the lecture over. So @johnpeart , what do you think? I know there's more to do, but let's get it integrated now and tidy up later.
> #109 implement notify

- LICENSE
- app/main/routes.py
- docker-compose.override.yml
- docs/404.html
- docs/Dockerfile
- docs/Gemfile
- docs/_docs/architecture.md
- docs/_docs/aws.md
- docs/_docs/contributing.md
- docs/_docs/cookies.md
- docs/_docs/getting-started.md
- docs/_docs/licences.md
- docs/_docs/notifications.md
- docs/_docs/privacy.md
- docs/_docs/second-test-document.md
- docs/_docs/test-document.md
- docs/index.md
Once this is completed, users will be able to read how to download and run this software locally. They'll also be aware of all of the technical things I can think of.
> Write docs

- .gitignore
- iac/terraform/.terraform.lock.hcl
- iac/terraform/README.md
- iac/terraform/apprunner.tf
- iac/terraform/backend.tf
- iac/terraform/data.tf
- iac/terraform/dns.tf
- iac/terraform/ecr.tf
- iac/terraform/ecs.tf
- iac/terraform/elasticache_redis.tf
- iac/terraform/iam.tf
- iac/terraform/module_state.tf
- iac/terraform/module_vpc.tf
- iac/terraform/outputs.tf
- iac/terraform/provider.tf
- iac/terraform/variables.tf
- iac/terraform/vpce.tf
Here's some Terraform I wrote last week to deploy MentorMatch to AWS within its own VPC. 
There are a few manual operations required, such as bringing in a domain as a Hosted Zone with Route53, and pushing the application docker images to ECR, which wouldn't have been optimal to terraform in this case. 
Hosting the service uses AWS App Runner and AWS Fargate, with a single node backend Redis in AWS Elasticache.
> Iac deployment with Terraform and AWS
